#!/usr/bin/env bash
# Installing nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

sed -i 's@^\tlocation / {@\tlocation /redirect_me {\n\t\treturn 301 $scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {@' /etc/nginx/sites-available/default