#!/usr/bin/env bash
# Displays Holberton School 10 times and prints hi on 9th iteration

i=0
while [ $i -lt 10 ]
do
    echo Holberton School
    ((i++))
    if [[ "$i" == 9 ]];
    then
        echo Hi
    fi
done
