#!/usr/bin/env bash
# Bash script which writes Holberton School.
# On 4th iteration bad luck.
# On 8th iteration good luck.

i=0
while [ $i -lt 10 ]
do
    if [[ "$i" == 3 ]];
    then
        echo bad luck
    elif [[ "$i" == 7 ]];
    then
        echo good luck
    else
        echo Holberton School
    fi
    ((i++))
done
