#!/usr/bin/env bash
# Bash script which writes numbers 1-20.
# On 4th iteration bad luck from China.
# On 8th iteration bad luck from Japan.
# On 17th iteration bad luck from Italy.

i=1
while [ $i -lt 21 ]
do
    echo "$i"
    if [[ "$i" == 4 ]];
    then
        echo bad luck from China
    elif [[ "$i" == 9 ]];
    then
        echo bad luck from Japan
    elif [[ "$i" == 17 ]];
    then
        echo bad luck from Italy
    fi
    ((i++))
done
