#!/usr/bin/env bash
# Bash script which writes numbers 1-20.
# On 4th iteration bad luck from China.
# On 8th iteration bad luck from Japan.
# On 17th iteration bad luck from Italy.

i=1
while [ $i -lt 21 ]
do
    echo "$i"
    case $i in
    4)
        echo bad luck from China
        ;;
    9)
        echo bad luck from Japan
        ;;
    17)
        echo bad luck from Italy
        ;;
    esac
    ((i++))
done
