#!/usr/bin/env bash
# Bash script which loops through a 12 hour clock

i=0
while [ $i -lt 13 ]
do
    echo Hour: "$i"
    j=0
    while [ $j -lt 60 ]
    do
        echo "$j"
        ((j++))
    done
    ((i++))
done
